
create table country(
    id bigint generated by default as identity
                    primary key,
    name varchar(255),
    continent varchar(255)
);
create table host
(
    id bigint generated by default as identity
                        primary key,
    name varchar(255),
    surname varchar(255),
    country_id bigint references country
);
create table accommodation(
    id  bigint generated by default as identity
                          primary key ,
    name varchar(255),
    description varchar(4000),
    category varchar(50),
    num_rooms int,
    host_id bigint references host
);

create table reservation(

    id bigint generated by default as identity
                        primary key,
    start_date date,
    end_date date,
    reservation_status varchar(50),
    accommodation_id bigint references accommodation
);

create table app_user(

    username                   varchar(255)
        primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);

